# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/Users/hewen/Stuffs/Winter2018/EECS 498/EECS-498-Vocaloid/vocaloid/gui/myapp/gui/mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.10
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class MainUI(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        MainWindow.setMinimumSize(QtCore.QSize(800, 600))
        MainWindow.setMaximumSize(QtCore.QSize(800, 600))
        font = QtGui.QFont()
        font.setFamily("ProFont for Powerline")
        MainWindow.setFont(font)
        MainWindow.setAutoFillBackground(True)
        MainWindow.setStyleSheet("QMainFrame { background-image: url(:background.jpeg) }")
        self.centralWidget = QtWidgets.QWidget(MainWindow)
        self.centralWidget.setObjectName("centralWidget")
        self.label = QtWidgets.QLabel(self.centralWidget)
        self.label.setGeometry(QtCore.QRect(110, 150, 641, 101))
        font = QtGui.QFont()
        font.setFamily("ProFont for Powerline")
        font.setItalic(False)
        self.label.setFont(font)
        self.label.setScaledContents(False)
        self.label.setObjectName("label")
        self.tutorialButton = QtWidgets.QPushButton(self.centralWidget)
        self.tutorialButton.setGeometry(QtCore.QRect(160, 360, 171, 71))
        self.tutorialButton.setStyleSheet("font: 36pt \"ProFont for Powerline\";")
        self.tutorialButton.setObjectName("tutorialButton")
        self.startButton = QtWidgets.QPushButton(self.centralWidget)
        self.startButton.setGeometry(QtCore.QRect(470, 360, 161, 71))
        self.startButton.setStyleSheet("font: 36pt \"ProFont for Powerline\";")
        self.startButton.setObjectName("startButton")
        MainWindow.setCentralWidget(self.centralWidget)
        self.menuBar = QtWidgets.QMenuBar(MainWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 800, 22))
        self.menuBar.setObjectName("menuBar")
        MainWindow.setMenuBar(self.menuBar)
        self.mainToolBar = QtWidgets.QToolBar(MainWindow)
        self.mainToolBar.setObjectName("mainToolBar")
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.mainToolBar)
        self.statusBar = QtWidgets.QStatusBar(MainWindow)
        self.statusBar.setObjectName("statusBar")
        MainWindow.setStatusBar(self.statusBar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Vocaloid"))
        self.label.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:64pt; color:#2a466f;\">Welcome to Vocaloid!</span></p></body></html>"))
        self.tutorialButton.setText(_translate("MainWindow", "TUTORIAL"))
        self.startButton.setText(_translate("MainWindow", "START"))

    def setupUi2(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        MainWindow.setMinimumSize(QtCore.QSize(800, 600))
        MainWindow.setMaximumSize(QtCore.QSize(800, 600))
        self.centralWidget = QtWidgets.QWidget(MainWindow)
        self.centralWidget.setObjectName("centralWidget")
        self.chooseButton = QtWidgets.QPushButton(self.centralWidget)
        self.chooseButton.setGeometry(QtCore.QRect(70, 160, 181, 141))
        font = QtGui.QFont()
        font.setFamily("ProFont for Powerline")
        font.setPointSize(36)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.chooseButton.setFont(font)
        self.chooseButton.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.chooseButton.setAutoFillBackground(False)
        self.chooseButton.setStyleSheet("font: 36pt \"ProFont for Powerline\";")
        self.chooseButton.setObjectName("chooseButton")
        self.label = QtWidgets.QLabel(self.centralWidget)
        self.label.setGeometry(QtCore.QRect(280, 210, 41, 31))
        font = QtGui.QFont()
        font.setFamily("ProFont for Powerline")
        font.setPointSize(18)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralWidget)
        self.label_2.setGeometry(QtCore.QRect(360, 30, 301, 41))
        font = QtGui.QFont()
        font.setFamily("ProFont for Powerline")
        font.setPointSize(36)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.nextButton = QtWidgets.QPushButton(self.centralWidget)
        self.nextButton.setGeometry(QtCore.QRect(630, 450, 121, 61))
        self.nextButton.setStyleSheet("font: 36pt \"ProFont for Powerline\";")
        self.nextButton.setObjectName("nextButton")
        self.textEdit = QtWidgets.QTextEdit(self.centralWidget)
        self.textEdit.setGeometry(QtCore.QRect(360, 80, 391, 351))
        self.textEdit.setStyleSheet("font: 24pt \"ProFont for Powerline\";")
        self.textEdit.setObjectName("textEdit")
        self.fileLabel = QtWidgets.QLabel(self.centralWidget)
        self.fileLabel.setGeometry(QtCore.QRect(80, 300, 161, 21))
        self.fileLabel.setStyleSheet("font: 18pt \"ProFont for Powerline\";")
        self.fileLabel.setObjectName("fileLabel")
        self.backButton = QtWidgets.QPushButton(self.centralWidget)
        self.backButton.setGeometry(QtCore.QRect(70, 450, 121, 61))
        self.backButton.setStyleSheet("font: 36pt \"ProFont for Powerline\";")
        self.backButton.setObjectName("backButton")
        MainWindow.setCentralWidget(self.centralWidget)
        self.menuBar = QtWidgets.QMenuBar(MainWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 800, 22))
        self.menuBar.setObjectName("menuBar")
        MainWindow.setMenuBar(self.menuBar)
        self.mainToolBar = QtWidgets.QToolBar(MainWindow)
        self.mainToolBar.setObjectName("mainToolBar")
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.mainToolBar)
        self.statusBar = QtWidgets.QStatusBar(MainWindow)
        self.statusBar.setObjectName("statusBar")
        MainWindow.setStatusBar(self.statusBar)

        self.retranslateUi2(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi2(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Vocaloid"))
        self.chooseButton.setText(_translate("MainWindow", "Choose\n"
"Lyrics\n"
"File"))
        self.label.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:36pt;\">OR</span></p></body></html>"))
        self.label_2.setText(_translate("MainWindow", "Type the lyrics:"))
        self.nextButton.setText(_translate("MainWindow", "NEXT"))
        self.textEdit.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'ProFont for Powerline\'; font-size:24pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.fileLabel.setText(_translate("MainWindow", "<html><head/><body><p>No file chosen.</p></body></html>"))
        self.backButton.setText(_translate("MainWindow", "BACK"))


    def setupUi3(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        MainWindow.setMinimumSize(QtCore.QSize(800, 600))
        MainWindow.setMaximumSize(QtCore.QSize(800, 600))
        self.centralWidget = QtWidgets.QWidget(MainWindow)
        self.centralWidget.setObjectName("centralWidget")
        self.label = QtWidgets.QLabel(self.centralWidget)
        self.label.setGeometry(QtCore.QRect(50, 140, 221, 71))
        self.label.setStyleSheet("font: 72pt \"ProFont for Powerline\";")
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralWidget)
        self.label_2.setGeometry(QtCore.QRect(50, 280, 251, 71))
        self.label_2.setStyleSheet("font: 72pt \"ProFont for Powerline\";")
        self.label_2.setObjectName("label_2")
        self.pitchLabel = QtWidgets.QLabel(self.centralWidget)
        self.pitchLabel.setGeometry(QtCore.QRect(380, 140, 381, 71))
        self.pitchLabel.setStyleSheet("font: 72pt \"ProFont for Powerline\";")
        self.pitchLabel.setText("")
        self.pitchLabel.setObjectName("pitchLabel")
        self.lengthLabel = QtWidgets.QLabel(self.centralWidget)
        self.lengthLabel.setGeometry(QtCore.QRect(380, 280, 381, 71))
        self.lengthLabel.setStyleSheet("font: 72pt \"ProFont for Powerline\";")
        self.lengthLabel.setText("")
        self.lengthLabel.setObjectName("lengthLabel")
        self.back2Button = QtWidgets.QPushButton(self.centralWidget)
        self.back2Button.setGeometry(QtCore.QRect(50, 450, 121, 61))
        self.back2Button.setStyleSheet("font: 36pt \"ProFont for Powerline\";")
        self.back2Button.setObjectName("back2Button")
        self.next2Button = QtWidgets.QPushButton(self.centralWidget)
        self.next2Button.setGeometry(QtCore.QRect(610, 450, 121, 61))
        self.next2Button.setStyleSheet("font: 36pt \"ProFont for Powerline\";")
        self.next2Button.setObjectName("next2Button")
        MainWindow.setCentralWidget(self.centralWidget)
        self.menuBar = QtWidgets.QMenuBar(MainWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 800, 22))
        self.menuBar.setObjectName("menuBar")
        MainWindow.setMenuBar(self.menuBar)
        self.mainToolBar = QtWidgets.QToolBar(MainWindow)
        self.mainToolBar.setObjectName("mainToolBar")
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.mainToolBar)
        self.statusBar = QtWidgets.QStatusBar(MainWindow)
        self.statusBar.setObjectName("statusBar")
        MainWindow.setStatusBar(self.statusBar)

        self.retranslateUi3(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi3(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Vocaloid"))
        self.back2Button.setText(_translate("MainWindow", "BACK"))
        self.next2Button.setText(_translate("MainWindow", "NEXT"))
        self.label.setText(_translate("MainWindow", "Pitch:"))
        self.label_2.setText(_translate("MainWindow", "Length:"))




